- name: Install PHP-FPM 8.3 and Nginx without Remi
  hosts: stapp02
  become: yes
  tasks:

    - name: Enable PHP 8.3 module (dnf)
      ansible.builtin.command: dnf module enable php:8.3 -y
      args:
        creates: /etc/alternatives/php

    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Install PHP-FPM 8.3 and CLI
      ansible.builtin.yum:
        name:
          - php
          - php-cli
          - php-fpm
        state: present
